#!/usr/bin/env bash
# Configures an Ubuntu server to change localhost and facebook.com IPs
grep -v "localhost\|facebook.com" /etc/hosts > /tmp/hosts.tmp
echo "127.0.0.2 localhost" >> /tmp/hosts.tmp
echo "8.8.8.8 facebook.com" >> /tmp/hosts.tmp
cp /tmp/hosts.tmp /etc/hosts
