#!/usr/bin/env bash
# Configures an Ubuntu server to change localhost and facebook.com IPs
sed -i 's/127.0.0.1\s*localhost/127.0.0.2 localhost/' /etc/hosts
grep -q "facebook.com" /etc/hosts && sed -i 's/.*facebook.com.*/8.8.8.8 facebook.com/' /etc/hosts || echo "8.8.8.8 facebook.com" >> /etc/hosts
