#!/usr/bin/env bash
# Configures an Ubuntu server to change localhost and facebook.com IPs
cp /etc/hosts /etc/hosts.bak
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
sed -i '/^127.0.0.1 localhost$/d' /etc/hosts
